# Generated by Django 5.2 on 2025-04-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0003_table_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='field',
            field=models.CharField(default='ABC', max_length=100),
        ),
    ]
