# Generated by Django 5.2 on 2025-04-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0004_category_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='field',
            field=models.CharField(max_length=100),
        ),
    ]
